name: Deploy release
on:
  push:
    tags:
      - '*'

concurrency:
  group: 'production'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ vars.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: www
        REMOTE_DIR: ${{ vars.REMOTE_DIR }}
        ARGS: --exclude-glob=content/*
