name: Release
on:
  push:
    tags:
      - '*'

concurrency:
  group: 'production'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Delete zero byte files
      # Fix a known bug with OpenSSL
      run: |
        find . -size 0c -exec rm -f {} \;
      shell: bash
    - uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ vars.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21
        protocol: ftps
        server-dir: ${{ vars.REMOTE_DIR }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          content/**
          src/**
          .*rc
          composer.*
          npm*
          package.json
          vite.config.js
          yarn*
